### ISSUE TITLE
Provide ARM image

### ISSUE THREAD

**Issue by winston0410** [urania-dev/snapp#28]
Hi, first of all thank you very much for your effort in creating this in SvelteKit. I notice there is no pipeline setup for this repo yet, and also an ARM image is missing. Is that something you would consider adding next? I can help once you decide which CICD provider to use

**Comment by urania-dev** [comment]
Hello and thank you first of all :)

To be honest, i don't have a real cd/ci pipeline (i actually don't know, and had not the time to actually learn the how-to) i build manually my images 

As for the arm image it should be easily buildable cloning the project on said env, if i recall it correctly

Tbf, as i posted in a closed issue, i will rebase the project taking some assumption (as put a stop to features requests in order to be able keep maintaining the project). 

It could require some times and i have less spare than i would. 

But im willingly to help you integrate your idea, meanwhile, to the project if you help me better understand the proceds

**Comment by urania-dev** [comment]
and i felt so bad about this, that i learned.

atm with buildx i can get an arm64 (working) and amd64 are working, arm/v7 hangup somewhere in the build process...

try uraniadev/snapp:0.8
