### ISSUE TITLE
Did something break?

### ISSUE THREAD

**Issue by firestrife23** [urania-dev/snapp#4]
Clicking on the Save button stopped working after you fixed the Geolocation. 😢

**Comment by marinkaberg** [comment]
Likely, Save button does not work

**Comment by urania-dev** [comment]
Mmmmh, have you the latest version with api?

I'll take a look and get back to you :)

**Comment by urania-dev** [comment]
You both right, I tried the api in the new url by dashboard, and forgot to remove the reference and get back with it at his natural state (via prisma client instead of bouncing to internal api). and mostly the api link was hardcoded for the test to the local area of development, hence its not working.

I'll put it back with the release i'm building now :)

it should work now, let me know and i'll close the issue :)

**Comment by marinkaberg** [comment]
Demo works fine, thank you!

Just discovered that there is a limitation for 2nd level domain name length, try to shorten https://ya.ru. I believe you'll fix it in a cople of seconds ;)

**Comment by urania-dev** [comment]
you are absolutely right. 

i'm uploading this version to ensure https and allow two letter tld
![immagine](https://github.com/urania-dev/snapp/assets/153094889/d5ca10b4-d4ce-4b1c-8035-4b4aed5ae1ca)

also closing the issue thank you very much!
